### ISSUE TITLE
With multiple windows open, drawing to each in a single event loop cycle takes 16ms per window

### ISSUE THREAD

**Issue by bitec0de** [notgull/theo#10]
..which seems suspicious as I can run five instances of the program, each drawing to a single window, without the slowdown.

This makes smoothly animating all of them at once impossible -- I want to do this so I can have at least one window open on each monitor of my PC, viewing different parts of one workspace across them all (which means some animations will be visible in multiple windows).

It's not a problem to only animate at full speed the one window the user is directly manipulating, but it'd be nice if they could all update at monitor refresh rate if possible.

Running on Windows 10 reveals vulkan errors, no idea if they're relevant:

`[2023-06-07T01:56:49Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x160cc92b3e0, name: ?)`

`[2023-06-07T01:56:49Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkDestroyFramebuffer-framebuffer-00892 (0xdb308312)]`

`Validation Error: [ VUID-vkDestroyFramebuffer-framebuffer-00892 ] Object 0: handle = 0x160cc92b3e0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xdb308312 | Cannot call vkDestroyFramebuffer on VkFramebuffer 0x7b3cde00000041fc[piet-wgpu render pass] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands thaty refer to framebuffer must have completed execution (https://vulkan.lunarg.com/doc/view/1.2.154.1/windows/1.2-extensions/vkspec.html#VUID-vkDestroyFramebuffer-framebuffer-00892)`

**Comment by notgull** [comment]
Odd, but thanks for the observation! I'll flamegraph to see what's causing the greatest source of slowdowns, once I get a chance.

As for the Vulkan errors... interesting, I would think that `wgpu` would use DX12 on Windows. Maybe that's the source of the slowdown? It might be worth checking.

**Comment by bitec0de** [comment]
Sorry, should've been clearer: it's taking an entire frame to repaint each separate window on all of macOS, Linux, and Windows, but the Vulkan errors only appear on Windows.

[This issue](https://github.com/gfx-rs/wgpu/issues/2719) says that DirectX isn't yet the WGPU default backend on Windows. The version of vulkan the error references is very out of date though, released sometime 2020, which is plausibly around the time I installed that OS which I hardly ever touch and haven't updated since (I just wanted to test some software).

**Comment by notgull** [comment]
The root cause of this is probably calling `Queue::submit()` once per window rather than once for the entire display setup. This could be worked around by exposing a method on `Display` that submits the queue that should be called on `RedrawEventsCleared`.
