### ISSUE TITLE
`RenderContext::save` resets the current transform to `Affine([1.0, 0.0, 0.0, 1.0, 0.0, 0.0])`, unlike the original Piet which leaves it unchanged

### ISSUE THREAD

**Issue by bitec0de** [notgull/theo#11]
Likewise, `RenderContext::with_save` resets the current transform within the closure, unlike Piet.

The original behaviour always let you reset by applying `Affine::inverse(ctx.current_transform())` if needed, but made it easy to draw something like '20 units to the left of the last thing' without having to keep track of the current transformation yourself.

**Comment by notgull** [comment]
Thanks for the catch!

I'm a [bit busy](https://scp-wiki.wikidot.com/romcon) at the moment, so I would appreciate it if you wrote a PR.

**Comment by bitec0de** [comment]
[Here's a quick fix](https://github.com/notgull/piet-hardware/pull/21) which treats the current transform correctly, but incorrectly resets the clip mask when `save` is called (instead of creating a new identical clip mask texture if one already exists).

However, clipping seems to be broken in general atm and I can't reproduce Piet's behaviour at all -- objects disappear entirely when just in the vicinity of the edge of a clip rectangle, for one thing. So I'm leaving that to possibly fix later, if that's ok. (There's already a TODO comment in the `MaskSlot::clip` function about it needing a rework.)

Good luck with the contest!

**Comment by bitec0de** [comment]
Would it be possible to add a special case for when clipping is a rectangle, using wgpu / OpenGL facilities? I don't think i've ever used a nonrectangular clipping region, but do definitely need those to work.

**Comment by notgull** [comment]
Reopening since it isn't really closed.

In my own experiments I thought that clipping was working. Can you show me your use case?

**Comment by bitec0de** [comment]
> Can you show me your use case?

Yes but my code is extremely bad and i'm shy about it so please give me a minute (i've just been modifying the examples without understanding them as i'm not a programmer). I added a clip rectangle with one corner in the center of the red rotating example star, and when drawing to a bitmap with piet and displaying to the screen with the `pixels` crate everything but the corner was cut from the star, but when drawing with Theo the star just disappeared entirely. With a clip rectangle set at (0,0) to (2000,2000) extent the red star was visible, but with (0,1) to (2000,2000) it vanished. With (200,200) to (3500,3500) it vanished, whereas the lower-right quarter was visible and correctly clipped in the piet+pixels drawn version.

Please don't let me distract you from whatever you're doing, this is not at all urgent for me right now, and i can happily wait for a few months.

**Comment by notgull** [comment]
Clipping should be fixed in https://github.com/notgull/piet-hardware/pull/39
