### ISSUE TITLE
Just noticed the color space gamma might be wrong

### ISSUE THREAD

**Issue by bitec0de** [notgull/theo#7]
This screenshot shows [the background color specified in the example code](https://g.co/kgs/bzBkeu), the example drawn by classic Piet and put on the screen using the Pixels crate in the middle, and then drawn by Theo on the right.

![theo_color_space](https://github.com/notgull/theo/assets/102129407/4d345828-9220-42c6-8851-30f947f41e84)

This is on Manjaro linux, and I get the same results on macOS.

**Comment by notgull** [comment]
Huh, interesting. Thanks for noticing!

[This code from `egui`](https://github.com/emilk/egui/blob/268a63fee2594175ef2e521229d2d97c75be0852/crates/egui_glow/src/shader/fragment.glsl#L19-L25) might provide a solution to this problem.

**Comment by notgull** [comment]
It looks like this only affects the `wgpu` backend.
